swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /dato_adicional_formacion_academica/:
    get:
      tags:
      - dato_adicional_formacion_academica
      description: get DatoAdicionalFormacionAcademica
      operationId: DatoAdicionalFormacionAcademicaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DatoAdicionalFormacionAcademica'
        "403":
          description: ""
    post:
      tags:
      - dato_adicional_formacion_academica
      description: create DatoAdicionalFormacionAcademica
      operationId: DatoAdicionalFormacionAcademicaController.Post
      parameters:
      - in: body
        name: body
        description: body for DatoAdicionalFormacionAcademica content
        required: true
        schema:
          $ref: '#/definitions/models.DatoAdicionalFormacionAcademica'
      responses:
        "201":
          description: '{int} models.DatoAdicionalFormacionAcademica'
        "403":
          description: body is empty
  /dato_adicional_formacion_academica/{id}:
    get:
      tags:
      - dato_adicional_formacion_academica
      description: get DatoAdicionalFormacionAcademica by id
      operationId: DatoAdicionalFormacionAcademicaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DatoAdicionalFormacionAcademica'
        "403":
          description: :id is empty
    put:
      tags:
      - dato_adicional_formacion_academica
      description: update the DatoAdicionalFormacionAcademica
      operationId: DatoAdicionalFormacionAcademicaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for DatoAdicionalFormacionAcademica content
        required: true
        schema:
          $ref: '#/definitions/models.DatoAdicionalFormacionAcademica'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DatoAdicionalFormacionAcademica'
        "403":
          description: :id is not int
    delete:
      tags:
      - dato_adicional_formacion_academica
      description: delete the DatoAdicionalFormacionAcademica
      operationId: DatoAdicionalFormacionAcademicaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /formacion_academica/:
    get:
      tags:
      - formacion_academica
      description: get FormacionAcademica
      operationId: FormacionAcademicaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.FormacionAcademica'
        "403":
          description: ""
    post:
      tags:
      - formacion_academica
      description: create FormacionAcademica
      operationId: FormacionAcademicaController.Post
      parameters:
      - in: body
        name: body
        description: body for FormacionAcademica content
        required: true
        schema:
          $ref: '#/definitions/models.FormacionAcademica'
      responses:
        "201":
          description: '{int} models.FormacionAcademica'
        "403":
          description: body is empty
  /formacion_academica/{id}:
    get:
      tags:
      - formacion_academica
      description: get FormacionAcademica by id
      operationId: FormacionAcademicaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.FormacionAcademica'
        "403":
          description: :id is empty
    put:
      tags:
      - formacion_academica
      description: update the FormacionAcademica
      operationId: FormacionAcademicaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for FormacionAcademica content
        required: true
        schema:
          $ref: '#/definitions/models.FormacionAcademica'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.FormacionAcademica'
        "403":
          description: :id is not int
    delete:
      tags:
      - formacion_academica
      description: delete the FormacionAcademica
      operationId: FormacionAcademicaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /soporte_formacion_academica/:
    get:
      tags:
      - soporte_formacion_academica
      description: get SoporteFormacionAcademica
      operationId: SoporteFormacionAcademicaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SoporteFormacionAcademica'
        "403":
          description: ""
    post:
      tags:
      - soporte_formacion_academica
      description: create SoporteFormacionAcademica
      operationId: SoporteFormacionAcademicaController.Post
      parameters:
      - in: body
        name: body
        description: body for SoporteFormacionAcademica content
        required: true
        schema:
          $ref: '#/definitions/models.SoporteFormacionAcademica'
      responses:
        "201":
          description: '{int} models.SoporteFormacionAcademica'
        "403":
          description: body is empty
  /soporte_formacion_academica/{id}:
    get:
      tags:
      - soporte_formacion_academica
      description: get SoporteFormacionAcademica by id
      operationId: SoporteFormacionAcademicaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SoporteFormacionAcademica'
        "403":
          description: :id is empty
    put:
      tags:
      - soporte_formacion_academica
      description: update the SoporteFormacionAcademica
      operationId: SoporteFormacionAcademicaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for SoporteFormacionAcademica content
        required: true
        schema:
          $ref: '#/definitions/models.SoporteFormacionAcademica'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SoporteFormacionAcademica'
        "403":
          description: :id is not int
    delete:
      tags:
      - soporte_formacion_academica
      description: delete the SoporteFormacionAcademica
      operationId: SoporteFormacionAcademicaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.DatoAdicionalFormacionAcademica:
    title: DatoAdicionalFormacionAcademica
    type: object
    properties:
      Activo:
        type: boolean
      FormacionAcademica:
        $ref: '#/definitions/models.FormacionAcademica'
      Id:
        type: integer
        format: int64
      TipoDatoAdicional:
        type: integer
        format: int64
      Valor:
        type: string
  models.FormacionAcademica:
    title: FormacionAcademica
    type: object
    properties:
      FechaFinalizacion:
        type: string
        format: datetime
      FechaInicio:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      Persona:
        type: integer
        format: int64
      Titulacion:
        type: integer
        format: int64
  models.SoporteFormacionAcademica:
    title: SoporteFormacionAcademica
    type: object
    properties:
      Documento:
        type: integer
        format: int64
      FormacionAcademica:
        $ref: '#/definitions/models.FormacionAcademica'
      Id:
        type: integer
        format: int64
tags:
- name: dato_adicional_formacion_academica
  description: |
    DatoAdicionalFormacionAcademicaController operations for DatoAdicionalFormacionAcademica
- name: formacion_academica
  description: |
    FormacionAcademicaController operations for FormacionAcademica
- name: soporte_formacion_academica
  description: |
    SoporteFormacionAcademicaController operations for SoporteFormacionAcademica
